package com.opensource.suggestionbox.dao.vo;

// Generated Jul 5, 2013 6:53:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SbUploadFiles generated by hbm2java
 */
@Entity
@Table(name = "sb_upload_files")
public class SbUploadFiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
	private byte[] attachment;

	public SbUploadFiles() {
	}

	public SbUploadFiles(String uuid) {
		this.uuid = uuid;
	}

	public SbUploadFiles(String uuid, byte[] attachment) {
		this.uuid = uuid;
		this.attachment = attachment;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 150)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "attachment")
	public byte[] getAttachment() {
		return this.attachment;
	}

	public void setAttachment(byte[] attachment) {
		this.attachment = attachment;
	}

}
