package com.metricstream.suggestionbox.dao.vo;

// Generated Jul 5, 2013 12:08:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SbUserPriv generated by hbm2java
 */
@Entity
@Table(name = "sb_user_priv")
public class SbUserPriv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
	private String owner;
	private String category;
	private Integer level;
	private String roles;
	private Integer rolesCode;

	public SbUserPriv() {
	}

	public SbUserPriv(String uuid) {
		this.uuid = uuid;
	}

	public SbUserPriv(String uuid, String owner, String category,
			Integer level, String roles, Integer rolesCode) {
		this.uuid = uuid;
		this.owner = owner;
		this.category = category;
		this.level = level;
		this.roles = roles;
		this.rolesCode = rolesCode;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 150)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "owner", length = 50)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "category", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "roles", length = 1000)
	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	@Column(name = "roles_code")
	public Integer getRolesCode() {
		return this.rolesCode;
	}

	public void setRolesCode(Integer rolesCode) {
		this.rolesCode = rolesCode;
	}

}
